export const textStyles = {
brand: { textAlign: 'center', marginBottom: '36px' }as React.CSSProperties,
Biglogo: {
    width: '60px',
    height: '60px',
    background: 'linear-gradient(135deg, var(--teal), #0070ff)',
    borderRadius: '16px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '18px',
    fontWeight: 700,
    color: '#fff',
    boxShadow: '0 0 30px rgba(0,212,200,.3)',
    marginBottom: '14px'
  } as React.CSSProperties,
SmallLogo: {
    width: '32px',
    height: '32px',
    background: 'linear-gradient(135deg,var(--teal),#0070ff)',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'var(--font-mono)',
    fontSize: '11px',
    fontWeight: 700,
    color: '#fff',
  }as React.CSSProperties,
h1: { fontSize: '26px', fontWeight: 800, margin: 0 } as React.CSSProperties,
h2: { fontSize: 32, fontWeight: 800, marginBottom: 12 }as React.CSSProperties,
p: { color: 'var(--muted)', fontSize: 15, lineHeight: 1.6, marginBottom: 30 }as React.CSSProperties,
}